### PR TITLE
 Throw on received message if the RoC of an all-nodes request has finished

### LINKED ISSUE #309: Terminated RequestOnConn fiber resumed on unexpected message
On a protocol mismatch the following situation can happen for an all-nodes request:
- Multiple `RequestOnConn` handler fibers are started, one for each node, and connect to the nodes.
- One of the fibers receives a message, fails to interpret correctly and terminates without shutting the connection down. (The fact that it does not initiate a shutdown is another issue; in any case the following should not happen.)
- When terminating, the fiber calls `RequestOnConnSet.finished`, which leaves the `RequestOnConn` object registered with the `RequestOnConnSet`. The request is still active because the other fibers haven't started handling the request yet.
- The node for which the client's `RequestOnConn` handler fiber has just terminated sends another message for the request.
- `Connection.setReceivedPayload` looks up the request by ID, from that it gets the -- terminated but still registered -- `RequestOnConn` handler by node address, and calls `setReceivedPayload`.
- `setReceivedPayload` attempts to resume the terminated `RequestOnConn` fiber. :boom:

The obvious solution would be to make `RequestOnConnSet.finished` remove the `RequestOnConn` object from the set. Then `Connection.setReceivedPayload` would not be able to find it. (It would then silently ignore the received message; if this is a good thing to do here may be subject to discussion.)

This is the original stack trace:
```
core.exception.AssertError@./submodules/swarm/src/swarm/neo/util/MessageFiber.d(559): attempt to resume a non-held fiber                                                                                                                                                                                                      
src/core/exception.d:438 _d_assert_msg
./submodules/swarm/src/swarm/neo/util/MessageFiber.d:559 _D5swarm3neo4util12MessageFiber17OceanMessageFiber6resumeMFS5swarm3neo4util12MessageFiber17OceanMessageFiber5TokenC6ObjectS5ocean4core10SmartUnion75__T10SmartUnionTS5swarm3neo4util12MessageFiber17OceanMessageFiber8Message_Z10SmartUnionZ9__requireMFZv
./submodules/swarm/src/swarm/neo/util/MessageFiber.d:558 ocean.core.SmartUnion.SmartUnion!(swarm.neo.util.MessageFiber.OceanMessageFiber.Message_).SmartUnion swarm.neo.util.MessageFiber.OceanMessageFiber.resume(swarm.neo.util.MessageFiber.OceanMessageFiber.Token, Object, ocean.core.SmartUnion.SmartUnion!(swarm.neo.util.MessageFiber.OceanMessageFiber.Message_).SmartUnion)./submodules/swarm/src/swarm/neo/connection/RequestOnConnBase.d:1734 void swarm.neo.connection.RequestOnConnBase.RequestOnConnBase.resumeFiber_(ocean.core.SmartUnion.SmartUnion!(swarm.neo.util.MessageFiber.OceanMessageFiber.Message_).SmartUnion)
./submodules/swarm/src/swarm/neo/connection/RequestOnConnBase.d:1779 void swarm.neo.connection.RequestOnConnBase.RequestOnConnBase.setReceivedPayload(const(void)[])
./submodules/swarm/src/swarm/neo/client/RequestOnConn.d:603 void swarm.neo.client.RequestOnConn.RequestOnConn.setReceivedPayload(const(void)[])
./submodules/swarm/src/swarm/neo/client/Connection.d:639 void swarm.neo.client.Connection.Connection.setReceivedPayload(ulong, const(void)[])
./submodules/swarm/src/swarm/neo/connection/ConnectionBase.d:651 void swarm.neo.connection.ConnectionBase.ConnectionBase.ReceiveLoop.receivedMessage(swarm.neo.protocol.Message.MessageType, const(void)[])
./submodules/swarm/src/swarm/neo/protocol/socket/MessageReceiver.d:214 void swarm.neo.protocol.socket.MessageReceiver.MessageReceiverBase.receive(lazy ocean.sys.Epoll.epoll_event_t.Event, scope void delegate(swarm.neo.protocol.Message.MessageType, const(void)[]), bool)
./submodules/swarm/src/swarm/neo/connection/ConnectionBase.d:603 void swarm.neo.connection.ConnectionBase.ConnectionBase.ReceiveLoop.fiberMethod()
src/core/thread.d:4277 void core.thread.Fiber.run()
src/core/thread.d:3523 fiber_entryPoint
```
Although we reproduced the same stack trace on a protocol mismatch and determined the aforementioned chain of events, it originally happened when a client using swarm v4.4.0 was connected to two nodes with a compatible protocol, and one of the nodes was restarted. We still need to figure out how this happens on a node restart.
We were unable to reproduce this behaviour with swarm v5.0.3.

### PR DESCRIPTION
**Pull request by david-eckardt-sociomantic**
In several situations, including a node shutdown and client/node protocol mismatch, the client can receive a message for a request-on-conn whose fiber has already terminated. Throw a protocol error to initiate a shutdown to prevent `RequestOnConn.setReceivedPayload` from attempting to resume the terminated fiber.

Fixes #309.

### CODE REVIEW

File: src/swarm/neo/client/RequestOnConnSet.d [hunk 1]
```diff
@@ -252,25 +252,29 @@ public struct RequestOnConnSet
 
     /***************************************************************************
 
-        Decrements the `num_active` counter and returns whether it is now 0.
+        Decrements the `num_active` counter, registers `roc` as inactive and
+        returns whether it is now 0.
```
Comment (gavin-norman-sociomantic) [inline src/swarm/neo/client/RequestOnConnSet.d]: Your addition to this sentence has changed the meaning of "it" at this point.

File: src/swarm/neo/client/RequestOnConnSet.d [hunk 2]
```diff
@@ -252,25 +252,29 @@ public struct RequestOnConnSet
...
+
+        Params:
+            roc = the `RequestOnConn` instance to register as inactive
```
Comment (gavin-norman-sociomantic) [inline src/swarm/neo/client/RequestOnConnSet.d]: Maybe "the `RequestOnConn` instance that has finished" is a bit clearer?

File: src/swarm/neo/client/RequestOnConnSet.d [hunk 3]
```diff
@@ -252,25 +252,29 @@ public struct RequestOnConnSet
...
         assert(this.num_active);
     }
     body
     {
-        // TODO: Consider `this.all_nodes.remove(request_on_conn)` instead of
-        // using the `active` flag. Not doing this now for a patch release to
-        // avoid potentially introducing a bug if there is an unobvious reason
-        // why it isn't done.
-        request_on_conn.active = false;
+        // TODO: Consider `this.all_nodes.remove(roc)` instead of using the
```
Comment (gavin-norman-sociomantic) [inline src/swarm/neo/client/RequestOnConnSet.d]: Actually, this would be better as an issue, rather than a code comment. We'll probably never think of it again, if it's left as a comment deep in the code like this.

File: src/swarm/neo/client/RequestOnConnSet.d [hunk 4]
```diff
@@ -264,6 +266,11 @@ public struct RequestOnConnSet
     }
     body
     {
+        // TODO: Consider `this.all_nodes.remove(request_on_conn)` instead of
+        // using the `active` flag. Not doing this now for a patch release to
+        // avoid potentially introducing a bug if there is an unobvious reason
+        // why it isn't done.
+        request_on_conn.active = false;
```
Comment (gavin-norman-sociomantic) [inline src/swarm/neo/client/RequestOnConnSet.d]: What does `request_on_conn` refer to? Looks like it's intended to be an argument, but the function has no arguments.

File: src/swarm/neo/client/RequestSet.d [hunk 5]
```diff
@@ -439,7 +439,8 @@ public final class RequestSet: IRequestSet
         }
         body
         {
-            if ( this.getRequestOnConnForNode(connection.remote_address) !is null )
+            if ( this.getRequestOnConnForNode(connection.remote_address,
```
Comment (gavin-norman-sociomantic) [inline src/swarm/neo/client/RequestSet.d]: Oh this is a weird case! This should be impossible, right? (If so, this is more like a `verify` than a protocol error.)

**Review by gavin-norman-sociomantic — COMMENTED** [review]
It'd be nice for the commit message to include a high-level summary of what the old and behaviour is, in this scenario.

File: src/swarm/neo/client/RequestSet.d (hunk 5 above)
Comment (david-eckardt-sociomantic) [reply src/swarm/neo/client/RequestSet.d]: Passing the exception here is merely for the sake of the arguments of `getRequestOnConnForNode`. I can add a `null` default for the exception parameter.

**Comment by david-eckardt-sociomantic** [comment]
Updated, addressing @gavin-norman-sociomantic's comments. Added issue #311.

**Review by gavin-norman-sociomantic — APPROVED** [review]
